In [1]:
#import numpy library
import numpy as np

In [2]:
#create one dimensional numpy array
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [3]:
#verify the data type in array
x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)


[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [4]:
#VERIFY THE DATA TYPE
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [5]:
# create a 2D array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [6]:
#reshape an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [8]:
# create an array with a range()
c = np.array(3,10)
print(c)
type(c)

TypeError: Cannot interpret '10' as a data type

In [9]:
#use of around()
d = np.array([1.3467, 3.10987,4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [16]:
# use of np.sqrt()
d
d = np.array([1.3467, 3.10987,4.912])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.912  ]
[1.16 1.76 2.22]


a1 = np.array([3,4,5,8],[7,2,8, np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

In [19]:
# mathematical operations on rows and cols
a2 =np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [21]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [24]:
# accessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4


array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])